"""T-40: the self-run loop. Started from the FastAPI lifespan; runs one
sweep immediately at boot (so the seeded demo scenario produces a REAL
alert with no user action) and then every `monitoring_interval_seconds`.

Fragility rules (build-plan risk flag 5, verbatim requirements):
- never raises into the request path — every sweep is fully caught, the
  loop always continues, status carries `last_error` instead;
- pausable at runtime (`enabled` flag via POST /monitoring/enabled);
- the boot sweep IS the "pre-seeded alert": generated by the real engine
  against the real seeded scenario, not a planted row.
"""

import asyncio
from datetime import datetime, timezone

from hubris.core import assumptions
from hubris.monitoring import watchdog

INTERVAL_SECONDS = assumptions.value("monitoring_interval_seconds")

status: dict = {
    "enabled": True,
    "interval_seconds": INTERVAL_SECONDS,
    "runs": 0,
    "last_run_at": None,
    "last_result": None,
    "last_error": None,
}

_task: asyncio.Task | None = None


def _sweep_once(state, stress_factor: float | None = None) -> dict:
    """Synchronous single sweep + status bookkeeping. Shared by the loop
    and POST /monitoring/run-once. Never raises."""
    try:
        result = watchdog.run_sweep(state, stress_factor=stress_factor)
        status["last_error"] = None
    except Exception as exc:  # noqa: BLE001 — belt over run_sweep's own braces
        result = {"targets_checked": [], "alerts_created": [], "errors": [str(exc)]}
        status["last_error"] = f"{type(exc).__name__}: {exc}"
    status["runs"] += 1
    status["last_run_at"] = datetime.now(timezone.utc).isoformat()
    status["last_result"] = result
    return result


async def _loop(state) -> None:
    # Boot sweep first: the demo scenario is already seeded, so monitoring
    # has something real to say from second zero.
    await asyncio.to_thread(_sweep_once, state)
    while True:
        await asyncio.sleep(INTERVAL_SECONDS)
        if not status["enabled"]:
            continue
        await asyncio.to_thread(_sweep_once, state)


def start(state) -> None:
    global _task
    if _task is None or _task.done():
        _task = asyncio.get_event_loop().create_task(_loop(state))


def stop() -> None:
    global _task
    if _task is not None:
        _task.cancel()
        _task = None
