"use client";

/**
 * REPORTS — engine-generated, downloadable, EDITABLE files. The backend
 * computes every figure (reports router); this page only requests and
 * downloads, then previews the same decision brief the .md export carries.
 */

import { useMemo, useState } from "react";
import DecisionBrief from "@/components/DecisionBrief";
import { exportUrl } from "@/lib/api";
import { useAtlas } from "@/lib/atlas-context";

export default function ReportsPage() {
  const { savedScenarios, scenarioId: globalScenarioId } = useAtlas();
  // Local selection, seeded from the workspace's active scenario.
  const [scenarioId, setScenarioId] = useState<string | null>(globalScenarioId);
  const [includeOptimizer, setIncludeOptimizer] = useState(false);

  const query = useMemo(() => {
    const params = new URLSearchParams();
    if (scenarioId) params.set("scenario_id", scenarioId);
    return params;
  }, [scenarioId]);

  const reportQuery = useMemo(() => {
    const params = new URLSearchParams(query);
    if (includeOptimizer) params.set("include_optimizer", "true");
    const s = params.toString();
    return s ? `?${s}` : "";
  }, [query, includeOptimizer]);

  const plainQuery = query.toString() ? `?${query.toString()}` : "";

  return (
    <div className="w-full h-full overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-8 flex flex-col gap-6">

        <header>
          <div className="flex items-center gap-2.5 mb-1">
            <span className="text-sm font-mono text-cyan-400">▦</span>
            <h1 className="text-lg font-bold text-white tracking-wide">Reports &amp; exports</h1>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Every file is generated by the engine on request — the browser only downloads.
          </p>
        </header>

        {/* ── Controls ── */}
        <div className="flex flex-wrap items-center gap-4 rounded-2xl px-5 py-4 bg-black/60 border border-white/10">
          <label className="flex items-center gap-2.5 text-xs text-slate-300">
            <span className="uppercase tracking-widest text-[10px] text-slate-500">Scenario</span>
            <select
              value={scenarioId ?? ""}
              onChange={(e) => setScenarioId(e.target.value || null)}
              className="text-xs px-2.5 py-1.5 rounded-lg bg-white/5 border border-white/10
                         text-slate-100 focus:outline-none focus:border-cyan-500/40 cursor-pointer"
            >
              <option value="">Baseline</option>
              {savedScenarios.map((s) => (
                <option key={s.id} value={s.id}>{s.label}</option>
              ))}
            </select>
          </label>

          <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
            <input
              type="checkbox"
              checked={includeOptimizer}
              onChange={(e) => setIncludeOptimizer(e.target.checked)}
              className="accent-[#E8112D]"
            />
            Include optimizer recommendation
            <span className="text-[10px] text-slate-500">(runs the solver server-side)</span>
          </label>
        </div>

        {/* ── Download cards ── */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <DownloadCard
            icon="▦"
            title="Executive Report"
            ext=".xlsx"
            desc="Summary, hubs, zones, flows and recommendations — styled workbook for leadership."
            href={exportUrl(`/export/report.xlsx${reportQuery}`)}
          />
          <DownloadCard
            icon="✎"
            title="Editable Network Data"
            ext=".xlsx"
            desc="Canonical dataset — edit in Excel and re-upload through the dataset button. Round-trip tested."
            href={exportUrl(`/export/network.xlsx${plainQuery}`)}
            accent
          />
          <DownloadCard
            icon="▤"
            title="Decision Brief"
            ext=".md"
            desc="The auto-generated leadership brief as clean markdown."
            href={exportUrl(`/export/report.md${plainQuery}`)}
          />
        </div>

        {/* ── Live preview ── */}
        <section className="rounded-2xl p-6 bg-black/60 border border-white/10">
          <div className="flex items-center gap-2.5 mb-4">
            <span className="text-[10px] font-mono text-cyan-400">▤</span>
            <h2 className="text-[10px] font-semibold uppercase tracking-[0.2em] text-cyan-200">
              Decision brief — live preview
            </h2>
          </div>
          <DecisionBrief scenarioId={scenarioId} />
        </section>
      </div>
    </div>
  );
}

function DownloadCard({
  icon, title, ext, desc, href, accent = false,
}: {
  icon: string; title: string; ext: string; desc: string; href: string; accent?: boolean;
}) {
  return (
    <a
      href={href}
      download
      className={`group flex flex-col gap-2 p-5 rounded-2xl border transition-all duration-200
        ${accent
          ? "bg-[#E8112D]/10 border-[#E8112D]/35 hover:border-[#E8112D]/60"
          : "bg-black/60 border-white/10 hover:border-white/30"}`}
      style={accent ? { boxShadow: "0 0 24px rgba(232,17,45,0.12)" } : undefined}
    >
      <span className="text-xl leading-none">{icon}</span>
      <span className="text-sm font-bold text-white">
        {title}
        <span className="ml-1.5 text-[10px] font-mono text-slate-500">{ext}</span>
      </span>
      <span className="text-[11px] text-slate-400 leading-relaxed">{desc}</span>
      <span
        className={`mt-1 text-[11px] font-semibold
          ${accent ? "text-red-200" : "text-cyan-300"} group-hover:translate-x-0.5 transition-transform`}
      >
        ⭳ Download
      </span>
    </a>
  );
}
