"""canonical schema

Revision ID: 61f30020dab4
Revises: 
Create Date: 2026-07-31 10:07:02.050145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61f30020dab4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('emirate', sa.String(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=False),
    sa.Column('handling_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('od_matrix',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('time_min', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('from_id', 'to_id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('emirate', sa.String(), nullable=False),
    sa.Column('demand', sa.Float(), nullable=False),
    sa.Column('sla_hours', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_assignments',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('hub_id', sa.String(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('zone_id', 'hub_id')
    )
    op.create_table('fleet_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('cost_per_km', sa.Float(), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=False),
    sa.Column('count_available', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_results',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('kpis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_results')
    op.drop_table('fleet_types')
    op.drop_table('current_assignments')
    op.drop_table('zones')
    op.drop_table('scenarios')
    op.drop_table('od_matrix')
    op.drop_table('hubs')
    # ### end Alembic commands ###
